//Projeto salvo no git
package GUI_class;
import class_pkg.*;
import java.util.Set;

public class MainFrame extends javax.swing.JFrame {
    public MainFrame() {
        initComponents();
        setLocationRelativeTo(null);
    }
    //Atributos IN
    static String Operacoes = "";
    static boolean PV = false;
    //FIM
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        BG = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        A = new javax.swing.JTextArea();
        jPanel2 = new javax.swing.JPanel();
        B1 = new javax.swing.JButton();
        B4 = new javax.swing.JButton();
        B7 = new javax.swing.JButton();
        B2 = new javax.swing.JButton();
        B5 = new javax.swing.JButton();
        B8 = new javax.swing.JButton();
        B6 = new javax.swing.JButton();
        B9 = new javax.swing.JButton();
        B3 = new javax.swing.JButton();
        B0 = new javax.swing.JButton();
        Bdot = new javax.swing.JButton();
        BDelete = new javax.swing.JButton();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel3 = new javax.swing.JPanel();
        Bigual = new javax.swing.JButton();
        Bmais = new javax.swing.JButton();
        Bmul = new javax.swing.JButton();
        Bmenos = new javax.swing.JButton();
        Bdiv = new javax.swing.JButton();
        Bexp = new javax.swing.JButton();
        Bopc = new javax.swing.JButton();
        Bclc = new javax.swing.JButton();
        Brad = new javax.swing.JButton();
        Brad2 = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        Bigual1 = new javax.swing.JButton();
        Bpor1 = new javax.swing.JButton();
        Bfat1 = new javax.swing.JButton();
        Blogn = new javax.swing.JButton();
        Bln = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        Bigual2 = new javax.swing.JButton();
        Bvir = new javax.swing.JButton();
        Bper = new javax.swing.JButton();
        Bcomb = new javax.swing.JButton();
        Barr = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        MPitem = new javax.swing.JCheckBoxMenuItem();
        MCitem = new javax.swing.JCheckBoxMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Calculadora");
        setResizable(false);

        jPanel1.setBackground(java.awt.SystemColor.controlDkShadow);

        A.setEditable(false);
        A.setBackground(new java.awt.Color(0, 0, 51));
        A.setColumns(20);
        A.setFont(new java.awt.Font("Arial", 0, 30)); // NOI18N
        A.setForeground(new java.awt.Color(255, 255, 255));
        A.setLineWrap(true);
        A.setRows(2);
        A.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 2));
        A.setCaretColor(new java.awt.Color(255, 255, 255));
        A.setDisabledTextColor(new java.awt.Color(255, 255, 255));
        jScrollPane1.setViewportView(A);

        jPanel2.setBackground(new java.awt.Color(153, 153, 153));
        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 3));

        B1.setBackground(new java.awt.Color(204, 204, 204));
        B1.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        B1.setText("1");
        B1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B1ActionPerformed(evt);
            }
        });

        B4.setBackground(new java.awt.Color(204, 204, 204));
        B4.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        B4.setText("4");
        B4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B4ActionPerformed(evt);
            }
        });

        B7.setBackground(new java.awt.Color(204, 204, 204));
        B7.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        B7.setText("7");
        B7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B7ActionPerformed(evt);
            }
        });

        B2.setBackground(new java.awt.Color(204, 204, 204));
        B2.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        B2.setText("2");
        B2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B2ActionPerformed(evt);
            }
        });

        B5.setBackground(new java.awt.Color(204, 204, 204));
        B5.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        B5.setText("5");
        B5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B5ActionPerformed(evt);
            }
        });

        B8.setBackground(new java.awt.Color(204, 204, 204));
        B8.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        B8.setText("8");
        B8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B8ActionPerformed(evt);
            }
        });

        B6.setBackground(new java.awt.Color(204, 204, 204));
        B6.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        B6.setText("6");
        B6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B6ActionPerformed(evt);
            }
        });

        B9.setBackground(new java.awt.Color(204, 204, 204));
        B9.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        B9.setText("9");
        B9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B9ActionPerformed(evt);
            }
        });

        B3.setBackground(new java.awt.Color(204, 204, 204));
        B3.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        B3.setText("3");
        B3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B3ActionPerformed(evt);
            }
        });

        B0.setBackground(new java.awt.Color(204, 204, 204));
        B0.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        B0.setText("0");
        B0.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B0ActionPerformed(evt);
            }
        });

        Bdot.setBackground(new java.awt.Color(204, 204, 204));
        Bdot.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        Bdot.setText(".");
        Bdot.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BdotActionPerformed(evt);
            }
        });

        BDelete.setBackground(new java.awt.Color(211, 130, 115));
        BDelete.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        BDelete.setText("D");
        BDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BDeleteActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(B1, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(B4, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(B7, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(B2, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(B5, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(B8, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(BDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(B0, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(B6, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(B9, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(B3, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Bdot, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(B2, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(B5, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(B8, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(B3, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(B6, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(B9, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Bdot, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(B0, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(BDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(B1, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(B4, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(B7, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(11, 11, 11))
        );

        jTabbedPane1.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N

        jPanel3.setBackground(new java.awt.Color(153, 153, 153));
        jPanel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 3));

        Bigual.setBackground(new java.awt.Color(204, 255, 204));
        Bigual.setFont(new java.awt.Font("Arial", 0, 48)); // NOI18N
        Bigual.setText("=");
        Bigual.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Fim(evt);
            }
        });

        Bmais.setBackground(new java.awt.Color(255, 255, 204));
        Bmais.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        Bmais.setText("+");
        Bmais.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BmaisActionPerformed(evt);
            }
        });

        Bmul.setBackground(new java.awt.Color(255, 255, 204));
        Bmul.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        Bmul.setText("x");
        Bmul.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BmulActionPerformed(evt);
            }
        });

        Bmenos.setBackground(new java.awt.Color(255, 255, 204));
        Bmenos.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        Bmenos.setText("-");
        Bmenos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BmenosActionPerformed(evt);
            }
        });

        Bdiv.setBackground(new java.awt.Color(255, 255, 204));
        Bdiv.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        Bdiv.setText("/");
        Bdiv.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BdivActionPerformed(evt);
            }
        });

        Bexp.setBackground(new java.awt.Color(255, 255, 204));
        Bexp.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        Bexp.setText("^");
        Bexp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BexpActionPerformed(evt);
            }
        });

        Bopc.setBackground(new java.awt.Color(204, 204, 255));
        Bopc.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        Bopc.setText("(");
        Bopc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BopcActionPerformed(evt);
            }
        });

        Bclc.setBackground(new java.awt.Color(204, 204, 255));
        Bclc.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        Bclc.setText(")");
        Bclc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BclcActionPerformed(evt);
            }
        });

        Brad.setBackground(new java.awt.Color(255, 255, 204));
        Brad.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        Brad.setText("²√");
        Brad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BradActionPerformed(evt);
            }
        });

        Brad2.setBackground(new java.awt.Color(255, 255, 204));
        Brad2.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        Brad2.setText("n√");
        Brad2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Brad2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Bigual, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Bmais, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Bopc, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Bmenos, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(20, 20, 20)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(Bdiv, javax.swing.GroupLayout.DEFAULT_SIZE, 65, Short.MAX_VALUE)
                                .addComponent(Bclc, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(Bmul, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Brad, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(20, 20, 20)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(Bexp, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(Brad2, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Bigual, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(11, 11, 11)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Bmais, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Bexp, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Bmul, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Bdiv, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Brad, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Bmenos, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Bclc, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Bopc, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Brad2, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Principal", jPanel3);

        jPanel4.setBackground(new java.awt.Color(153, 153, 153));
        jPanel4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 3));

        Bigual1.setBackground(new java.awt.Color(204, 255, 204));
        Bigual1.setFont(new java.awt.Font("Arial", 0, 48)); // NOI18N
        Bigual1.setText("=");
        Bigual1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Bigual1Fim(evt);
            }
        });

        Bpor1.setBackground(new java.awt.Color(255, 255, 204));
        Bpor1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        Bpor1.setText("%");
        Bpor1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Bpor1ActionPerformed(evt);
            }
        });

        Bfat1.setBackground(new java.awt.Color(255, 255, 204));
        Bfat1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        Bfat1.setText("!");
        Bfat1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Bfat1ActionPerformed(evt);
            }
        });

        Blogn.setBackground(new java.awt.Color(255, 255, 204));
        Blogn.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        Blogn.setText("log(n)");
        Blogn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BlognActionPerformed(evt);
            }
        });

        Bln.setBackground(new java.awt.Color(255, 255, 204));
        Bln.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        Bln.setText("ln");
        Bln.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BlnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Bigual1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(Bpor1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(Bfat1, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(20, 20, 20)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Blogn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(Bln, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE))))
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Bigual1, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(11, 11, 11)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Bpor1, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Blogn, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Bfat1, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Bln, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(100, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("   +   ", jPanel4);

        jPanel5.setBackground(new java.awt.Color(153, 153, 153));
        jPanel5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 3));

        Bigual2.setBackground(new java.awt.Color(204, 255, 204));
        Bigual2.setFont(new java.awt.Font("Arial", 0, 48)); // NOI18N
        Bigual2.setText("=");
        Bigual2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Bigual2Fim(evt);
            }
        });

        Bvir.setBackground(new java.awt.Color(204, 204, 255));
        Bvir.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        Bvir.setText(",");
        Bvir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BvirActionPerformed(evt);
            }
        });

        Bper.setBackground(new java.awt.Color(255, 255, 204));
        Bper.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        Bper.setText("P n");
        Bper.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BperActionPerformed(evt);
            }
        });

        Bcomb.setBackground(new java.awt.Color(255, 255, 204));
        Bcomb.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        Bcomb.setText("C n, p");
        Bcomb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BcombActionPerformed(evt);
            }
        });

        Barr.setBackground(new java.awt.Color(255, 255, 204));
        Barr.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        Barr.setText("A n, p");
        Barr.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BarrActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Bigual2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(Bvir, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(20, 20, 20)
                        .addComponent(Bper, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE))
                    .addComponent(Bcomb, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Barr, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Bigual2, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(11, 11, 11)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Bvir, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Bper, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12)
                .addComponent(Bcomb, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addComponent(Barr, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jTabbedPane1.addTab("   ++   ", jPanel5);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jScrollPane1)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 10, Short.MAX_VALUE)
                        .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jMenu1.setText("Tema");

        BG.add(MPitem);
        MPitem.setSelected(true);
        MPitem.setText("Padrão");
        MPitem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MPitemActionPerformed(evt);
            }
        });
        jMenu1.add(MPitem);

        BG.add(MCitem);
        MCitem.setText("Claro");
        MCitem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MCitemActionPerformed(evt);
            }
        });
        jMenu1.add(MCitem);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void B1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B1ActionPerformed
        if(PV){
            A.setText("");
            PV = false;
        }
        Operacoes += "1";
        A.append("1");
    }//GEN-LAST:event_B1ActionPerformed

    private void B2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B2ActionPerformed
        if(PV){
            A.setText("");
            PV = false;
        }
        Operacoes += "2";
        A.append("2");
    }//GEN-LAST:event_B2ActionPerformed

    private void B3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B3ActionPerformed
        if(PV){
            A.setText("");
            PV = false;
        }
        Operacoes += "3";
        A.append("3");
    }//GEN-LAST:event_B3ActionPerformed

    private void B4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B4ActionPerformed
        if(PV){
            A.setText("");
            PV = false;
        }
        Operacoes += "4";
        A.append("4");
    }//GEN-LAST:event_B4ActionPerformed

    private void B5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B5ActionPerformed
        if(PV){
            A.setText("");
            PV = false;
        }
        Operacoes += "5";
        A.append("5");
    }//GEN-LAST:event_B5ActionPerformed

    private void B6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B6ActionPerformed
        if(PV){
            A.setText("");
            PV = false;
        }
        Operacoes += "6";
        A.append("6");
    }//GEN-LAST:event_B6ActionPerformed

    private void B7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B7ActionPerformed
        if(PV){
            A.setText("");
            PV = false;
        }
        Operacoes += "7";
        A.append("7");
    }//GEN-LAST:event_B7ActionPerformed

    private void B8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B8ActionPerformed
        if(PV){
            A.setText("");
            PV = false;
        }
        Operacoes += "8";
        A.append("8");
    }//GEN-LAST:event_B8ActionPerformed

    private void B9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B9ActionPerformed
        if(PV){
            A.setText("");
            PV = false;
        }
        Operacoes += "9";
        A.append("9");
    }//GEN-LAST:event_B9ActionPerformed

    private void B0ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B0ActionPerformed
        if(PV){
            A.setText("");
            PV = false;
        }
        Operacoes += "0";
        A.append("0");
    }//GEN-LAST:event_B0ActionPerformed

    private void BmaisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BmaisActionPerformed
        if(PV){
            A.setText("");
            PV = false;
        }
        Operacoes += "+";
        A.append(" + ");
    }//GEN-LAST:event_BmaisActionPerformed

    private void BmenosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BmenosActionPerformed
        if(PV){
            A.setText("");
            PV = false;
        }
        Operacoes += "-";
        A.append(" - ");
    }//GEN-LAST:event_BmenosActionPerformed

    private void BmulActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BmulActionPerformed
        if(PV){
            A.setText("");
            PV = false;
        }
        Operacoes += "*";
        A.append(" * ");
    }//GEN-LAST:event_BmulActionPerformed

    private void BdivActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BdivActionPerformed
        if(PV){
            A.setText("");
            PV = false;
        }
        Operacoes += "/";
        A.append(" / ");
    }//GEN-LAST:event_BdivActionPerformed

    private void Fim(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Fim
        if(null == A.getText()) {
            PV = true;
            A.setText("");
            Operacoes O = new Operacoes(Operacoes);
            float resultado = O.main();
            boolean verifica = O.getvalidade();
            if (verifica) {
                String R = Float.toString(resultado);
                A.append(R);
            } else {
                A.append("Erro");
            }
            Operacoes = "";
        } else switch (A.getText()) {
            case "Erro":
                A.setText("");
                break;
            case "":
                A.setText("");
                break;
            default:
                PV = true;
                A.setText("");
                Operacoes O = new Operacoes(Operacoes);
                float resultado = O.main();
                boolean verifica = O.getvalidade();
                if (verifica) {
                    String R = Float.toString(resultado);
                    A.append(R);
                } else {
                    A.append("Erro");
                }   Operacoes = "";
                break;
        }
    }//GEN-LAST:event_Fim

    private void BdotActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BdotActionPerformed
        if(PV){
            A.setText("");
            PV = false;
        }
        Operacoes += ".";
        A.append(".");
    }//GEN-LAST:event_BdotActionPerformed

    private void BexpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BexpActionPerformed
        if(PV){
            A.setText("");
            PV = false;
        }
        Operacoes += "^";
        A.append(" ^ ");
    }//GEN-LAST:event_BexpActionPerformed

    private void BopcActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BopcActionPerformed
        if(PV){
            A.setText("");
            PV = false;
        }
        Operacoes += "(";
        A.append("(");
    }//GEN-LAST:event_BopcActionPerformed

    private void BclcActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BclcActionPerformed
        if(PV){
            A.setText("");
            PV = false;
        }
        Operacoes += ")";
        A.append(")");
    }//GEN-LAST:event_BclcActionPerformed

    private void BradActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BradActionPerformed
        if(PV){
            A.setText("");
            PV = false;
        }
        Operacoes += "r";
        A.append("²√");
    }//GEN-LAST:event_BradActionPerformed

    private void BDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BDeleteActionPerformed
        if (Operacoes != null || !"".equals(Operacoes)) {
            String aux = "";
            String Opf = "";
            char[] Op_char = Operacoes.toCharArray();
            int i = 0;
            A.setText("");
            while (i < Op_char.length - 1) {
                if(Op_char[i] == '+'
                        || Op_char[i] == '-'
                        || Op_char[i] == '*'
                        || Op_char[i] == '/'
                        || Op_char[i] == '^'){
                    A.append(" ");
                    aux += Op_char[i];
                    A.append(aux);
                    aux = "";
                    A.append(" ");
                }else if(Op_char[i] == 'r'){
                    aux += "²√";
                    A.append(aux);
                    aux = "";
                }else if(Op_char[i] == ','){
                    aux += ", ";
                    A.append(aux);
                    aux = "";
                }else if(Op_char[i] == 'T'){
                    aux += "P ";
                    A.append(aux);
                    aux = "";
                }else if(Op_char[i] == 'M'){
                    aux += "C ";
                    A.append(aux);
                    aux = "";
                }else if(Op_char[i] == 'J'){
                    aux += "A ";
                    A.append(aux);
                    aux = "";
                }else if(Op_char[i] == '!'){
                    aux += "!";
                    A.append(aux);
                    aux = "";
                }else if(Op_char[i] == 'l'){
                    aux += "ln";
                    A.append(aux);
                    aux = "";
                }else if(Op_char[i] == 'L'){
                    aux += "log";
                    A.append(aux);
                    aux = "";
                }else if(Op_char[i] == 'p'){
                    aux += "%";
                    A.append(aux);
                    aux = "";
                }else if(Op_char[i] == 'R'){
                    aux += "√";
                    A.append(aux);
                    aux = "";
                }else{
                    aux += Op_char[i];
                    A.append(aux);
                    aux = "";
                }
                Opf += Op_char[i];
                i++;
            }
            Operacoes = Opf;
            
        }
    }//GEN-LAST:event_BDeleteActionPerformed

    private void Brad2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Brad2ActionPerformed
        if(PV){
            A.setText("");
            PV = false;
        }
        Operacoes += "R";
        A.append("√");
    }//GEN-LAST:event_Brad2ActionPerformed

    private void Bigual1Fim(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Bigual1Fim
        if(null == A.getText()) {
            PV = true;
            A.setText("");
            Operacoes O = new Operacoes(Operacoes);
            float resultado = O.main();
            boolean verifica = O.getvalidade();
            if (verifica) {
                String R = Float.toString(resultado);
                A.append(R);
            } else {
                A.append("Erro");
            }
            Operacoes = "";
        } else switch (A.getText()) {
            case "Erro":
                A.setText("");
                break;
            case "":
                A.setText("");
                break;
            default:
                PV = true;
                A.setText("");
                Operacoes O = new Operacoes(Operacoes);
                float resultado = O.main();
                boolean verifica = O.getvalidade();
                if (verifica) {
                    String R = Float.toString(resultado);
                    A.append(R);
                } else {
                    A.append("Erro");
                }   Operacoes = "";
                break;
        }
    }//GEN-LAST:event_Bigual1Fim

    private void Bpor1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Bpor1ActionPerformed
        if(PV){
            A.setText("");
            PV = false;
        }
        Operacoes += "p";
        A.append("%");
    }//GEN-LAST:event_Bpor1ActionPerformed

    private void Bfat1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Bfat1ActionPerformed
        if(PV){
            A.setText("");
            PV = false;
        }
        Operacoes += "!";
        A.append("!");
    }//GEN-LAST:event_Bfat1ActionPerformed

    private void BlognActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BlognActionPerformed
        if(PV){
            A.setText("");
            PV = false;
        }
        Operacoes += "L";
        A.append("log");
    }//GEN-LAST:event_BlognActionPerformed

    private void BlnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BlnActionPerformed
        if(PV){
            A.setText("");
            PV = false;
        }
        Operacoes += "l";
        A.append("ln");
    }//GEN-LAST:event_BlnActionPerformed

    private void Bigual2Fim(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Bigual2Fim
        if(null == A.getText()) {
            PV = true;
            A.setText("");
            Operacoes O = new Operacoes(Operacoes);
            float resultado = O.main();
            boolean verifica = O.getvalidade();
            if (verifica) {
                String R = Float.toString(resultado);
                A.append(R);
            } else {
                A.append("Erro");
            }
            Operacoes = "";
        } else switch (A.getText()) {
            case "Erro":
                A.setText("");
                break;
            case "":
                A.setText("");
                break;
            default:
                PV = true;
                A.setText("");
                Operacoes O = new Operacoes(Operacoes);
                float resultado = O.main();
                boolean verifica = O.getvalidade();
                if (verifica) {
                    String R = Float.toString(resultado);
                    A.append(R);
                } else {
                    A.append("Erro");
                }   Operacoes = "";
                break;
        }
    }//GEN-LAST:event_Bigual2Fim

    private void BvirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BvirActionPerformed
        if(PV){
            A.setText("");
            PV = false;
        }
        Operacoes += ",";
        A.append(", ");
    }//GEN-LAST:event_BvirActionPerformed

    private void BperActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BperActionPerformed
        if(PV){
            A.setText("");
            PV = false;
        }
        Operacoes += "T";
        A.append("P ");
    }//GEN-LAST:event_BperActionPerformed

    private void BcombActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BcombActionPerformed
        if(PV){
            A.setText("");
            PV = false;
        }
        Operacoes += "M";
        A.append("C ");
    }//GEN-LAST:event_BcombActionPerformed

    private void BarrActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BarrActionPerformed
        if(PV){
            A.setText("");
            PV = false;
        }
        Operacoes += "J";
        A.append("A ");
    }//GEN-LAST:event_BarrActionPerformed

    private void MPitemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MPitemActionPerformed
        //Painel principal
        jPanel1.setBackground(java.awt.SystemColor.controlDkShadow);
        //Area de texto
        A.setBackground(new java.awt.Color(0, 0, 51));
        A.setFont(new java.awt.Font("Arial", 0, 30)); // NOI18N
        A.setForeground(new java.awt.Color(255, 255, 255));
        A.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 2));
        //Painel de números
        jPanel2.setBackground(new java.awt.Color(153, 153, 153));
        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 3));
        //Painel de abas e abas
        jTabbedPane1.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jPanel3.setBackground(new java.awt.Color(153, 153, 153));
        jPanel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 3));
        jPanel4.setBackground(new java.awt.Color(153, 153, 153));
        jPanel4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 3));
        jPanel5.setBackground(new java.awt.Color(153, 153, 153));
        jPanel5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 3));
        //Botões
        B0.setBackground(new java.awt.Color(204, 204, 204));
        B1.setBackground(new java.awt.Color(204, 204, 204));
        B2.setBackground(new java.awt.Color(204, 204, 204));
        B3.setBackground(new java.awt.Color(204, 204, 204));
        B4.setBackground(new java.awt.Color(204, 204, 204));
        B5.setBackground(new java.awt.Color(204, 204, 204));
        B6.setBackground(new java.awt.Color(204, 204, 204));
        B7.setBackground(new java.awt.Color(204, 204, 204));
        B8.setBackground(new java.awt.Color(204, 204, 204));
        B9.setBackground(new java.awt.Color(204, 204, 204));
        Bdot.setBackground(new java.awt.Color(204, 204, 204));
        BDelete.setBackground(new java.awt.Color(211, 130, 115));
        BDelete.setForeground(new java.awt.Color(0, 0, 0));
        
        Bigual.setBackground(new java.awt.Color(204, 255, 204));
        Bigual.setForeground(new java.awt.Color(0, 0, 0));
        Bmais.setBackground(new java.awt.Color(255, 255, 204));
        Bmenos.setBackground(new java.awt.Color(255, 255, 204));
        Bmul.setBackground(new java.awt.Color(255, 255, 204));
        Bdiv.setBackground(new java.awt.Color(255, 255, 204));
        Brad.setBackground(new java.awt.Color(255, 255, 204));
        Brad2.setBackground(new java.awt.Color(255, 255, 204));
        Bexp.setBackground(new java.awt.Color(255, 255, 204));
        Bopc.setBackground(new java.awt.Color(204, 204, 255));
        Bclc.setBackground(new java.awt.Color(204, 204, 255));
        
        Bigual1.setBackground(new java.awt.Color(204, 255, 204));
        Bigual1.setForeground(new java.awt.Color(0, 0, 0));
        Bpor1.setBackground(new java.awt.Color(255, 255, 204));
        Bfat1.setBackground(new java.awt.Color(255, 255, 204));
        Blogn.setBackground(new java.awt.Color(255, 255, 204));
        Bln.setBackground(new java.awt.Color(255, 255, 204));
        
        Bigual2.setBackground(new java.awt.Color(204, 255, 204));
        Bigual2.setForeground(new java.awt.Color(0, 0, 0));
        Bvir.setBackground(new java.awt.Color(204, 204, 255));
        Bper.setBackground(new java.awt.Color(255, 255, 204));
        Bcomb.setBackground(new java.awt.Color(255, 255, 204));
        Barr.setBackground(new java.awt.Color(255, 255, 204));
    }//GEN-LAST:event_MPitemActionPerformed

    private void MCitemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MCitemActionPerformed
        //Painel principal
        jPanel1.setBackground(new java.awt.Color(240, 240, 240));
        //Area de texto
        A.setBackground(new java.awt.Color(255, 255, 255));
        A.setFont(new java.awt.Font("Arial", 0, 30)); // NOI18N
        A.setForeground(new java.awt.Color(0, 0, 0));
        A.setBorder(javax.swing.BorderFactory.createLineBorder(java.awt.SystemColor.controlDkShadow, 2));
        //Painel de números
        jPanel2.setBackground(new java.awt.Color(204, 204, 204));
        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(java.awt.SystemColor.controlDkShadow, 3));
        //Painel de abas e abas
        jTabbedPane1.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jPanel3.setBackground(new java.awt.Color(204, 204, 204));
        jPanel3.setBorder(javax.swing.BorderFactory.createLineBorder(java.awt.SystemColor.controlDkShadow, 3));
        jPanel4.setBackground(new java.awt.Color(204, 204, 204));
        jPanel4.setBorder(javax.swing.BorderFactory.createLineBorder(java.awt.SystemColor.controlDkShadow, 3));
        jPanel5.setBackground(new java.awt.Color(204, 204, 204));
        jPanel5.setBorder(javax.swing.BorderFactory.createLineBorder(java.awt.SystemColor.controlDkShadow, 3));
        //Botões
        B0.setBackground(new java.awt.Color(220, 220, 220));
        B1.setBackground(new java.awt.Color(220, 220, 220));
        B2.setBackground(new java.awt.Color(220, 220, 220));
        B3.setBackground(new java.awt.Color(220, 220, 220));
        B4.setBackground(new java.awt.Color(220, 220, 220));
        B5.setBackground(new java.awt.Color(220, 220, 220));
        B6.setBackground(new java.awt.Color(220, 220, 220));
        B7.setBackground(new java.awt.Color(220, 220, 220));
        B8.setBackground(new java.awt.Color(220, 220, 220));
        B9.setBackground(new java.awt.Color(220, 220, 220));
        Bdot.setBackground(new java.awt.Color(220, 220, 220));
        BDelete.setBackground(new java.awt.Color(255, 64, 64));
        BDelete.setForeground(new java.awt.Color(255, 255, 255));
        
        
        Bigual.setBackground(new java.awt.Color(0, 255, 0));
        Bigual.setForeground(new java.awt.Color(0, 100, 0));
        
        Bmais.setBackground(new java.awt.Color(255, 255, 0));
        Bmenos.setBackground(new java.awt.Color(255, 255, 0));
        Bmul.setBackground(new java.awt.Color(255, 255, 0));
        Bdiv.setBackground(new java.awt.Color(255, 255, 0));
        Brad.setBackground(new java.awt.Color(255, 255, 0));
        Brad2.setBackground(new java.awt.Color(255, 255, 0));
        Bexp.setBackground(new java.awt.Color(255, 255, 0));
        Bopc.setBackground(new java.awt.Color(135, 206, 255));
        Bclc.setBackground(new java.awt.Color(135, 206, 255));
        
        Bigual1.setBackground(new java.awt.Color(0, 255, 0));
        Bigual1.setForeground(new java.awt.Color(0, 100, 0));
        
        Bpor1.setBackground(new java.awt.Color(255, 255, 0));
        Bfat1.setBackground(new java.awt.Color(255, 255, 0));
        Blogn.setBackground(new java.awt.Color(255, 255, 0));
        Bln.setBackground(new java.awt.Color(255, 255, 0));
        
        Bigual2.setBackground(new java.awt.Color(0, 255, 0));
        Bigual2.setForeground(new java.awt.Color(0, 100, 0));
        
        Bvir.setBackground(new java.awt.Color(135, 206, 255));
        Bper.setBackground(new java.awt.Color(255, 255, 0));
        Bcomb.setBackground(new java.awt.Color(255, 255, 0));
        Barr.setBackground(new java.awt.Color(255, 255, 0));        
    }//GEN-LAST:event_MCitemActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea A;
    private javax.swing.JButton B0;
    private javax.swing.JButton B1;
    private javax.swing.JButton B2;
    private javax.swing.JButton B3;
    private javax.swing.JButton B4;
    private javax.swing.JButton B5;
    private javax.swing.JButton B6;
    private javax.swing.JButton B7;
    private javax.swing.JButton B8;
    private javax.swing.JButton B9;
    private javax.swing.JButton BDelete;
    private javax.swing.ButtonGroup BG;
    private javax.swing.JButton Barr;
    private javax.swing.JButton Bclc;
    private javax.swing.JButton Bcomb;
    private javax.swing.JButton Bdiv;
    private javax.swing.JButton Bdot;
    private javax.swing.JButton Bexp;
    private javax.swing.JButton Bfat1;
    private javax.swing.JButton Bigual;
    private javax.swing.JButton Bigual1;
    private javax.swing.JButton Bigual2;
    private javax.swing.JButton Bln;
    private javax.swing.JButton Blogn;
    private javax.swing.JButton Bmais;
    private javax.swing.JButton Bmenos;
    private javax.swing.JButton Bmul;
    private javax.swing.JButton Bopc;
    private javax.swing.JButton Bper;
    private javax.swing.JButton Bpor1;
    private javax.swing.JButton Brad;
    private javax.swing.JButton Brad2;
    private javax.swing.JButton Bvir;
    private javax.swing.JCheckBoxMenuItem MCitem;
    private javax.swing.JCheckBoxMenuItem MPitem;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTabbedPane jTabbedPane1;
    // End of variables declaration//GEN-END:variables
}
